[package]
name = "AlgorithmsRust"
version = "0.1.0"
authors = ["João Paulo Seregatte Costa <joao.costa@itelios.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
